services:
  - type: web
    name: music-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install --workspace server
    startCommand: npm run start --workspace server
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: LASTFM_API_KEY
        sync: false
      - key: TASTEDIVE_API_KEY
        sync: false
      - key: JAMENDO_CLIENT_ID
        sync: false
